### ISSUE TITLE
Scully Build Process Error

### ISSUE THREAD

**Issue by pjlamb12** [Jefiozie/nx-jefiozie#4]
I started implementing the plugin acording to the README, and get the following error:

```
---------
 We encountered an error executing the config file. "./scully.personal-site.config.ts"
 Check the error below, and try again later
---------
Error: Cannot find module '/Users/pjlamb12/projects/personal-website/node_modules/scully-plugin-time-to-read/src\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/pjlamb12/projects/personal-website/scully.personal-site.config.js:5:36)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/pjlamb12/projects/personal-website/node_modules/scully-plugin-time-to-read/package.json',
  requestPath: 'scully-plugin-time-to-read'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 15
npm ERR! personal-site@0.0.0 scully: `scully`
npm ERR! Exit status 15
npm ERR!
npm ERR! Failed at the personal-site@0.0.0 scully script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pjlamb12/.npm/_logs/2020-12-22T06_05_58_299Z-debug.log
```

Here's the relevant part of my Scully config file:

```
setPluginConfig(timeToRead, {
	path: '/blog',
} as timeToReadOptions);

```

I also tried `path: './blog'`, but got the same error.

**Comment by Jefiozie** [comment]
Hi @pjlamb12, ohw that doesnt seems right, let me check it and come back to you.

Just to check, did you have the latest version ofnthe package? Also if you could share the scully version i can verify it with that version.

Thanks

**Comment by pjlamb12** [comment]
```
"scully-plugin-time-to-read": "0.0.2",
"@scullyio/scully": "^1.0.8",
```

**Comment by Jefiozie** [comment]
Hey @pjlamb12, I've made an example to see if I could reproduce your problem. However, I'm not able to our I'm having something different than you. My example repo can be found [here](https://github.com/Jefiozie/scully-demo-meetup-and-timetoread). Would it be possible for you to verify If you see a difference with your setup vs mine?

**Comment by pjlamb12** [comment]
I mean, I can't see any noticeable differences. I have no idea why it's not working for me. I'll keep playing with it, but thanks for the help. :) I'm excited to use this plugin!

**Comment by Jefiozie** [comment]
I can have a better look if you have the repo public? I think it is a minor detail we are not seeing. Let me know how things go and If I can be of any assistants.

**Comment by Jefiozie** [comment]
Hi @pjlamb12, I think I found the problem, could you give it a try with version `0.0.3` and let me know if it is resolved?

**Comment by pjlamb12** [comment]
Here's what I got this time:

![image](https://user-images.githubusercontent.com/2006222/103033188-20b57e00-451f-11eb-80ae-780477e89551.png)

**Comment by Jefiozie** [comment]
Would it be possible to share your repo? Then I can have a closer look for you?

**Comment by pjlamb12** [comment]
I just added you to the repo. I am doing this on the time-to-read branch

**Comment by Jefiozie** [comment]
Thank you for sharing this, the good news is that I have found the problem but I need to think a bit about how I can resolve this in a good way. Hopefully, I will publish a new version tomorrow morning (GMT time) otherwise it will be after christmas.

**Comment by pjlamb12** [comment]
That's great news, but don't rush it because of me. Spending time doing other things is especially important during the holidays. 😀

**Comment by Jefiozie** [comment]
Hi @pjlamb12, I just pushed a new release (0.0.4) and I've made a commit to the repo updating the version of the package. This should resolve the issue you've experienced. Sorry for the inconvenience.

**Comment by Jefiozie** [comment]
Forgot to mention this, you should now just run `npm run scully --scanroutes` and it should work ;)

**Comment by pjlamb12** [comment]
Wow, thanks for that! I'll definitely try it out. Have a great Christmas with your family!

**Comment by Jefiozie** [comment]
No problem, im closing this for now. Let me knoq if you jed firther assistants. Merry Christmas to you and your family and thanks for using my plugin.
